### ISSUE TITLE
What is the difference between unic_locale and unic_locale_impl?

### ISSUE THREAD

**Issue by sffc** [zbraniecki/unic-locale#47]
I don't really understand why there are all these crates.  Can you explain?  When should a user depend on `unic_locale` and when should they depend on `unic_locale_impl`?

**Comment by zbraniecki** [comment]
This is an artifact of a limitation of the current Rust.

We have a feature called procedural macro. It's a very powerful feature which allows us to construct well formed language identifiers and locales at zero-runtime-cost.
It looks like this:

```rust
use unic_langid::langid;

let lang_pl = langid!("pl-Latn-PL");
```

At build time, this macro will be parsed using `LanguageIdentifier` parser, and the compilation will fail if the langid is invalid. If it passes that, the code for runtime (invisible to the developer) will be a constructed that looks more like this:

```rust
let lang_pl = LanguageIdentifier::from_parts_unchecked(
    Some(TinyStr8::from_bytes_unchecked(52342)),
    Some(TinyStr4::from_bytes_unchecked(4234)),
    Some(TinyStr4::from_bytes_unchecked(64542)),
    None
);
```

This call is "free", and can work as const.

This basically obsoleted the need for ICU's "Locale::EN", "Locale::DE" etc.

The challenge is that proc-macros are not fully ready yet and currently there are many restrictions to use them in Rust stable. @dtolnay worked around this problem with https://github.com/dtolnay/proc-macro-hack which allows for proc macros on stable, but unfortunately require two separate crates for the macro use - `-macros` and `-macros-impl` handle that.

Now, since the macro requires the parser to parse the string, we have to use 4 crates: the code implementation, the macro implementation, the macro called, and the "final" crate that uses `-impl` and optionally `-macros`.

I know it's suboptimal, and I hope that with the current roadmap planning for Rust 2020, proc macros will get stabilized and this will go away.

I tried to post a tl;dr in https://github.com/zbraniecki/unic-locale#meta-crate - if you have an idea how to explain it better, I'd appreciate help!

**Comment by zbraniecki** [comment]
@sffc - does it answer your question? Do you see a way to improve README to make it easier to understand?

**Comment by sffc** [comment]
Hmm.  I think the GitHub readme explains this pretty well; does that belong on the API docs as well?  The GitHub readme is not as discoverable.

Will we be able to clean this up before v1, or do the timeframes not align to make that happen?

**Comment by zbraniecki** [comment]
> Will we be able to clean this up before v1, or do the timeframes not align to make that happen?

I don't have an answer to that yet. It depends when we decide to shoot for v1.0. One of the missing pieces is some unified test coverage between ICU and this to validate the conformance.

In other words, I don't know what's missing yet.

**Comment by zbraniecki** [comment]
I'm going to close this issue as not actionable. We're still waiting for the rust ecosystem to mature either in direction of WATT or stabilizing proc macros
